name: OS-lab1

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: docker-build/Dockerfile
    environment:
      - BUILD_DIR=${BUILD_DIR}
      - TARGET=${TARGET}
    env_file:
      - ../.env